# debug: false                 # debug mode (default: false)
my_url: "https://google.com"   # надо так надо.. (optional)

# Database connection config
database:
    # host: "127.0.0.1"        # DB host (default: 127.0.0.1)
    port: 54321                # DB port (default: 5432)
    user: "test"               # DB user (required)
    pass: "pwd123"             # DB Port (required)
    ssl: true                  # use ssl (default: false)

# Server config
server:
    bind:
        - "10.0.0.1"
        - "127.0.0.1"
    # port: 8888               # Listen port (default, 8888)
    log_level: 999             # log level (1:error|2:warn|3:notice, dafault: 2)
